// Codes culled from the following sources.  These seem to be pretty consistent
// across vendors(???), but the description of the problems vary so should not
// be considered definitive here.
//
// - https://www.automationdirect.com/microsites/clickplcs/click-help/Content/241.htm
// - https://www.hmisource.com/otasuke/files/manual/gpproex/v2_71/device/data/odva_exp.pdf
// - https://www.hilscher.com/fileadmin/cms_upload/de/Resources/pdf/EtherNetIP_Adapter_V3_Protocol_API_04_EN.pdf
const STATUS_CODES = [
  [0x00, null, 'Success', ],
  [0x01, null, 'Connection failure', ],
  [0x01, 0x0100, 'Connection in use/Duplicate forward open', ],
  [0x01, 0x0103, 'Transport class/Trigger combination not supported', ],
  [0x01, 0x0106, 'Multiple configuration attempts', ],
  [0x01, 0x0107, 'Target connection not found', ],
  [0x01, 0x0108, 'Unsupported connection type', ],
  [0x01, 0x0109, 'Connection size mismatch', ],
  [0x01, 0x0110, 'Connection unconfigured', ],
  [0x01, 0x0111, 'RPI not supported', ],
  [0x01, 0x0113, 'Conn Mgr out of connections', ],
  [0x01, 0x0114, 'Vendor ID or product code mismatch', ],
  [0x01, 0x0115, 'Device type mismatch', ],
  [0x01, 0x0116, 'Revision mismatch', ],
  [0x01, 0x0117, 'Nonexistent instance number', ],
  [0x01, 0x0118, 'Bad config instance number', ],
  [0x01, 0x0119, 'No controlling connection open', ],
  [0x01, 0x011a, 'Target object out of connections', ],
  [0x01, 0x011c, 'The transport class requested in the Transport Type/Trigger parameter is not supported', ],
  [0x01, 0x011d, 'The production trigger requested in the Transport Type/Trigger parameter is not supported', ],
  [0x01, 0x011e, 'The direction requested in the Transport Type/Trigger parameter is not supported', ],
  [0x01, 0x011f, 'O2T fixed variable flag not supported', ],
  [0x01, 0x0120, 'T2O fixed / variable flag not supported', ],
  [0x01, 0x0121, 'O2T priority code not supported', ],
  [0x01, 0x0122, 'T2O priority code not supported', ],
  [0x01, 0x0123, 'Invalid originator to target network connection type', ],
  [0x01, 0x0124, 'Invalid target to originator network connection type', ],
  [0x01, 0x0125, 'O2T Redundant Owner flag not supported', ],
  [0x01, 0x0126, 'Invalid data segment', ],
  [0x01, 0x0127, 'Invalid originator to target size', ],
  [0x01, 0x0128, 'Invalid target to originator size', ],
  [0x01, 0x0129, 'Invalid connection path', ],
  [0x01, 0x012a, 'Invalid consuming application path', ],
  [0x01, 0x012b, 'Invalid producing application path', ],
  [0x01, 0x012c, 'Configuration Symbol does not exist', ],
  [0x01, 0x012d, 'Consuming Symbol does not exist', ],
  [0x01, 0x012e, 'Producing Symbol does not exist', ],
  [0x01, 0x012f, 'Inconsistent application path combination', ],
  [0x01, 0x0130, 'Data segment is not consistent with consumed data format', ],
  [0x01, 0x0131, 'Data segment is not consistent with produced data format', ],
  [0x01, 0x0132, 'Null forward open function not supported', ],
  [0x01, 0x0203, 'Using a timed out connection', ],
  [0x01, 0x0204, 'Unconnected Send timed out', ],
  [0x01, 0x0205, 'Unconnected Send param error', ],
  [0x01, 0x0301, 'No buffer memory available', ],
  [0x01, 0x0302, 'Insufficient bandwidth left', ],
  [0x01, 0x0303, 'Out of gen screeners', ],
  [0x01, 0x0304, 'Not configured to send RT data', ],
  [0x01, 0x0305, 'SIG does not match sig store in CCM', ],
  [0x01, 0x0306, 'CCM is not responding to req', ],
  [0x01, 0x0311, 'Nonexistent port', ],
  [0x01, 0x0312, 'Invalid link address in path', ],
  [0x01, 0x0315, 'Invalid segment in connection path', ],
  [0x01, 0x0315, 'Invalid segment in path', ],
  [0x01, 0x0316, 'Path and conn not equal in close', ],
  [0x01, 0x0317, 'Net seg not present or bad', ],
  [0x01, 0x0318, 'Link address to self invalid', ],
  [0x01, 0x0319, 'Resources in secondary unavail', ],
  [0x01, 0x031d, 'Redundant connection mismatch', ],
  [0x01, 0x0813, 'Not configurable for off-subnet multicast', ],
  [0x02, null, 'Resource unavailable', ],
  [0x03, null, 'Invalid parameter value', ],
  [0x04, null, 'Path segment error', ],
  [0x05, null, 'Path destination error', ],
  [0x06, null, 'Partial transfer', ],
  [0x07, null, 'Connection lost', ],
  [0x08, null, 'Service not supported', ],
  [0x09, null, 'Error in data segment', ],
  [0x0a, null, 'Attribute list error', ],
  [0x0b, null, 'Already in requested mode/state', ],
  [0x0c, null, 'Object state conflict', ],
  [0x0d, null, 'Object already exists', ],
  [0x0e, null, 'Attribute not settable', ],
  [0x0f, null, 'Privilege violation', ],
  [0x0e, null, 'Attribute not settable', ],
  [0x10, null, 'Device state conflict', ],
  [0x11, null, 'Reply data too large', ],
  [0x12, null, 'Fragmentation of a primitive value', ],
  [0x13, null, 'Not enough data', ],
  [0x14, null, 'Attribute not supported', ],
  [0x15, null, 'Too much data', ],
  [0x16, null, 'Object does not exist', ],
  [0x17, null, 'Service fragmentation sequence not in progress', ],
  [0x18, null, 'No stored attribute data', ],
  [0x19, null, 'Store operation failure', ],
  [0x1a, null, 'Request packet too large', ],
  [0x1b, null, 'Response packet too large', ],
  [0x1c, null, 'Missing attribute list entry data', ],
  [0x1d, null, 'Invalid attribute value list', ],
  [0x1e, null, 'Embedded service error', ],
  [0x1f, null, 'Vendor specific error', ],
  [0x20, null, 'Invalid parameter', ],
  [0x21, null, 'Write-once value or medium already written', ],
  [0x22, null, 'Invalid reply received', ],
  [0x25, null, 'Key failure in path', ],
  [0x26, null, 'Path size invalid', ],
  [0x27, null, 'Unexpected attribute in list', ],
  [0x28, null, 'Invalid member ID', ],
  [0x29, null, 'Member not settable', ],
  [0x2a, null, 'Group 2 only server general failure', ],
];

function getInfo(err) {
  return STATUS_CODES.find(v => v[0] == err.generalStatusCode && v[1] == err.extendedStatus) ||
    STATUS_CODES.find(v => v[0] == err.generalStatusCode && v[1] == null);
}

exports.getStatus = function(err) {
  const info = getInfo(err);
  return info && info[2];
}
